version: '2'
services:
  redis:
    image: redis
    container_name: rediscache
    command: redis-server --requirepass redispass
    expose:
      - 6379

  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:  
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    links:
      - redis
    environment:
      - REDISCLOUD_URL=redis://:redispass@rediscache:6379
